### ISSUE TITLE
按readme步骤部署，日志报错，k8s控制平台无数据

### ISSUE THREAD

**Issue by vnline** [n9e/k8s-mon#1]
env:
kubernetes-v1.15.4
dokcer 20.10.2
n9e:3.5.1

分别执行以下步骤：
kubectl apply -f k8s-config/kube-stats-metrics
kubectl apply -f k8s-config

k8s-mon-deployment 抛出错日志：

level=error ts=2021-02-23T16:35:46.274+08:00 caller=common.go:437 msg=GetServerAddrByGetPodErrorNoValue funcName:=coredns
level=error ts=2021-02-23T16:35:46.274+08:00 caller=kube_coredns.go:21 msg=GetServerSideAddrEmpty funcName:=coredns
level=error ts=2021-02-23T16:35:46.274+08:00 caller=common.go:437 msg=GetServerAddrByGetPodErrorNoValue funcName:=etcd
level=error ts=2021-02-23T16:35:46.274+08:00 caller=kube_etcd.go:21 msg=GetServerSideAddrEmpty funcName:=etcd
level=error ts=2021-02-23T16:35:46.274+08:00 caller=common.go:437 msg=GetServerAddrByGetPodErrorNoValue funcName:=kube-scheduler
level=error ts=2021-02-23T16:35:46.274+08:00 caller=kube_scheduler.go:21 msg=GetServerSideAddrEmpty funcName:=kube-scheduler
level=error ts=2021-02-23T16:35:46.274+08:00 caller=common.go:437 msg=GetServerAddrByGetPodErrorNoValue funcName:=kube-controller-manager
level=error ts=2021-02-23T16:35:46.274+08:00 caller=kube_controller_manager.go:19 msg=GetServerSideAddrEmpty funcName:=kube-controller-manager
level=error ts=2021-02-23T16:35:46.274+08:00 caller=common.go:437 msg=GetServerAddrByGetPodErrorNoValue funcName:=api-server
level=error ts=2021-02-23T16:35:46.275+08:00 caller=kube_apiserver.go:27 msg=GetServerSideAddrEmpty funcName:=api-server
level=error ts=2021-02-23T16:35:46.275+08:00 caller=common.go:437 msg=GetServerAddrByGetPodErrorNoValue funcName:=kube-proxy
level=error ts=2021-02-23T16:35:46.275+08:00 caller=common.go:534 msg=GetServerSideAddrEmpty funcName:=kube-proxy
level=error ts=2021-02-23T16:35:46.283+08:00 caller=common.go:463 msg=CurlTlsMetricsResError func_name=kubelet_node err:="reading text format failed: text format parsing error in line 1: unexpected end of input stream" seq=1/5 addr=https://10.129.0.122:10250/metrics
level=error ts=2021-02-23T16:35:46.284+08:00 caller=common.go:463 msg=CurlTlsMetricsResError func_name=kubelet_node err:="reading text format failed: text format parsing error in line 1: unexpected end of input stream" seq=4/5 addr=https://10.129.0.151:10250/metrics
level=error ts=2021-02-23T16:35:46.284+08:00 caller=common.go:463 msg=CurlTlsMetricsResError func_name=kubelet_node err:="reading text format failed: text format parsing error in line 1: unexpected end of input stream" seq=5/5 addr=https://10.129.0.152:10250/metrics
level=error ts=2021-02-23T16:35:46.284+08:00 caller=common.go:463 msg=CurlTlsMetricsResError func_name=kubelet_node err:="reading text format failed: text format parsing error in line 1: unexpected end of input stream" seq=2/5 addr=https://10.129.0.146:10250/metrics
level=error ts=2021-02-23T16:35:46.285+08:00 caller=common.go:463 msg=CurlTlsMetricsResError func_name=kubelet_node err:="reading text format failed: text format parsing error in line 1: unexpected end of input stream" seq=3/5 addr=https://10.129.0.148:10250/metrics
level=info ts=2021-02-23T16:35:46.291+08:00 caller=get_pod.go:99 msg=server_pod_ips_result num_kubeSchedulerIps=0 num_kubeControllerIps=0 num_apiServerIps=0 num_coreDnsIps=0 num_kubeProxyIps=0 num_etcdIps=0 time_took_seconds=0.01653417

**Comment by ning1875** [comment]
看起来像是鉴权没过的问题，加我微信 ning1875   ，远程给你看下吧
