### ISSUE TITLE
failed for volume "secret-volume" : secret "etcd-certs" not found

### ISSUE THREAD

**Issue by eagle9527** [n9e/k8s-mon#2]
没有etcd-certs 报错，托管版本的k8s 没有etcd 证书起不来 
![QQ图片20210329162940](https://user-images.githubusercontent.com/5716348/112808905-11107d00-90ac-11eb-9d32-194414a38320.png)

**Comment by UlricQin** [comment]
托管版本，云厂商会帮你做监控和高可用，有些组件就可以不监控了

**Comment by eagle9527** [comment]
谢谢，去掉就正常了

**Comment by ning1875** [comment]
> 没有etcd-certs 报错，托管版本的k8s 没有etcd 证书起不来
> ![QQ图片20210329162940](https://user-images.githubusercontent.com/5716348/112808905-11107d00-90ac-11eb-9d32-194414a38320.png)

不对吧，etcd只是其中的一个采集job，即使证书不对也只影响这一个job，k8s-mon会正常启动的，你这个只是个warning吧。确认下pod能否正常启动

**Comment by ning1875** [comment]
> > 没有etcd-certs 报错，托管版本的k8s 没有etcd 证书起不来
> > ![QQ图片20210329162940](https://user-images.githubusercontent.com/5716348/112808905-11107d00-90ac-11eb-9d32-194414a38320.png)
> 
> 不对吧，etcd只是其中的一个采集job，即使证书不对也只影响这一个job，k8s-mon会正常启动的，你这个只是个warning吧。确认下pod能否正常启动

我的错，我试了下，在pod中写了挂载而对应的 volume不存在的话 ，pod是启动不起来的
