### ISSUE TITLE
导入大盘后不能正常显示

### ISSUE THREAD

**Issue by CodeRusher** [n9e/k8s-mon#5]
导入大盘json文件后，大盘不能正常显示（里面是空的）
n9e版本：5.4.0-ga.0

另，分类标签都是显示[object] [object] ...

**Comment by UlricQin** [comment]
升级到最新版本

**Comment by CodeRusher** [comment]
升级n9e版本么？
n9e用最新的helm安装，版本：5.11.3
也不行呢，还是一样的现象

**Comment by CodeRusher** [comment]
是不是k8s-mon里面的大盘配置太老了呢？
